### PR TITLE
Feature/restrictions compilation

### PR DESCRIPTION
**Pull request by mattdean-digicatapult**
Adds restriciton compilation to `dscp-lang`

Majority of the changes here are to add the `build` command to `dscp-lang`. There are some additional more general changes to the runtime that we're needed to get this working. Notably:
1. New restriction type `FixedInputMetadataValueType`
2. Abstraction of types from `dscp-node-runtime` to a subpackage `dscp-runtime-types`. This is to prevent `dscp-lang` becoming dependent on the very heavy runtime
3. Increase max program length to 501 (inc. weight change)

The compiler changes themselvers are fairly complex and relatviely poorly tested. I would like to improve test coverage and refactoring (esp. tools/lang/src/compiler/condition_transform.rs) but I think this can wait for now.

Companion PRs for this:
* https://github.com/digicatapult/dscp-process-management/pull/160
* https://github.com/digicatapult/dscp-matchmaker-api/pull/214

### CODE REVIEW

**Review by dblane-digicatapult — CHANGES_REQUESTED** [review]
Maybe I've missed it, but I don't see any additional documentation for how to build the language compiler?  Are we doing this as a part of CI anywhere?

**Comment by mattdean-digicatapult** [comment]
`dscp-lang` will build when building the workspace but you're right I'm missing usage documentation

**Review by dblane-digicatapult — APPROVED** [review]
Looks ok, a bit of a monstrous PR.  I trust the items you said need doing are already in a backlog somewhere?

**Review by n3op2 — APPROVED** [review]
Boom! nice one, eyes did not catch anything

**Pull request merged**
